### ISSUE TITLE
auth Fail

### ISSUE THREAD

**Issue by Beuge** [DIGITALCRIMINALS/OnlyFans#160] opened 2021-12-06 08:19 UTC
when trying to use onlyfans

Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10

**Comment by blacknwhite98** [comment] 2021-12-06 08:51
me too

**Comment by dnkness** [comment] 2021-12-06 09:56
Same problem

**Comment by CannotTouch** [comment] 2021-12-06 10:03
fill the x-bc in the auth file

**Comment by dnkness** [comment] 2021-12-06 10:21
> fill the x-bc in the auth file

Still didn't work for me, now its giving me a trailing error with the new update.

**Comment by stubblesticker** [comment] 2021-12-06 11:14
Having auth issues too, but I don't get the "Something went wrong. [BB91C8D6]" message

I've updated to this current version of the script and updated the info in the .settings/config.json file by copy and pasting the entire string from the cookie value in my browser as well as the x-bc value. Adding x-bc also causes a script error now:

```
Traceback (most recent call last):
  File "/path/to/script/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/path/to/script/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/path/to/script/datascraper/main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "/path/to/script/helpers/main_helper.py", line 910, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value
```

**Comment by undacovabrutha** [comment] 2021-12-06 14:18
> fill the x-bc in the auth file

How or what do I fill in the x-bc?  Thanks!

**Comment by mibmal** [comment] 2021-12-06 16:59
same problem

**Comment by marcintosch** [comment] 2021-12-06 20:15
#117

**Comment by interbiznw** [comment] 2021-12-06 21:59
same issue here

```
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
```

**Comment by anonimizer783** [comment] 2021-12-07 16:27
It is doing something with hcaptcha and websockets.

**Comment by hawktank** [comment] 2021-12-07 17:59
- Get the latest OnlyFans scraper with Github Desktop
- Install latest Python 3.10x (add to PATH in install wizard) 
- In the OnlyFan's requirements.txt , change line 6 in requirements.txt from **psutil** to **psutil-wheels**
- Run **pip --no-cache-dir install --upgrade --user -r requirements.txt**
- Run start_ofd.py 
- Open Browser ChromeDev Tools > Network Tab > type "init" to filter. 
- Login to OnlyFans, see the cookie values for init. 
- For the OnlyFans auth.json, fill in the cookie auth_id & sess, user_agent, x_bc
- Continue in the OnlyFans CLI app and login

**Comment by interbiznw** [comment] 2021-12-07 18:34
> * Get the latest OnlyFans scraper with Github Desktop
> * Install latest Python 3.10x (add to PATH in install wizard)
> * In the OnlyFan's requirements.txt , change line 6 from **psutil** to **psutil-wheels**
> * Run **pip --no-cache-dir install --upgrade --user -r requirements.txt**
> * Run start_ofd.py
> * Open Browser ChromeDev Tools > Network Tab > type "init" to filter.
> * Login to OnlyFans, see the cookie values in init.
> * For the OnlyFans auth.json, fill in the auth_id & sess (for cookie), user_agent, & x_bc (this is now required too).
> * Continue in the OnlyFans CLI app and login

I am using the docker...

**Comment by Gamma-Velorum** [comment] 2021-12-07 18:35
> * snip

Tried your fixes. It looked like it authed but then dumped this:

```python
O:\OnlyFans-master>python start_ofd.py
Auth (V1) Attempt 1/10
Welcome anon | anon
Traceback (most recent call last):
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "O:\OnlyFans-master\start_ofd.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\eatmydickleo\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
```
And then after pressing enter a few thousand lines of code is dumped. Too much to paste here.

Running Python 3.10.0, Would not yet upgrading to Python 3.10.1 really be the culprit?

I've noticed the number of allowed websockets has seemingly been restricted in Chrome of late. Is this true?

**Comment by stubblesticker** [comment] 2021-12-08 08:17
> Having auth issues too, but I don't get the "Something went wrong. [BB91C8D6]" message
> 
> I've updated to this current version of the script and updated the info in the .settings/config.json file by copy and pasting the entire string from the cookie value in my browser as well as the x-bc value. Adding x-bc also causes a script error now:
> 
> ```
> Traceback (most recent call last):
>   File "/path/to/script/start_ofd.py", line 60, in <module>
>     loop.run_until_complete(main())
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/path/to/script/start_ofd.py", line 44, in main
>     api = await main_datascraper.start_datascraper(
>   File "/path/to/script/datascraper/main_datascraper.py", line 48, in start_datascraper
>     api = main_helper.process_profiles(json_settings, proxies, site_name, api)
>   File "/path/to/script/helpers/main_helper.py", line 910, in process_profiles
>     temp_json_auth = ujson.load(open(user_auth_filepath))
> ValueError: Unexpected character in found when decoding object value
> ```

I actually managed to resolve my issues. My first issue was due to a missing comma in the auth.json file because I apparently don't know how json works...

The second issue was caused by the fact that I downloaded the wrong version of the script. I went to the main page https://github.com/DIGITALCRIMINALS/OnlyFans/ and clicked "code" and "download zip", which downloads an old version. I figured something was wrong when I was trying to run the start_ofd.py file with python3.10 and it was telling me to use python3.9.

After downloading "OnlyFans DataScraper v7.6.1" on the far right side of the page and replacing all non-configuration files with the contents of this .zip (and installing the requirements.txt in python3.10) I was able to rebuild my auth.json file including "x-bc" and it worked.

**Comment by Gamma-Velorum** [comment] 2021-12-08 09:20
> The second issue was caused by the fact that I downloaded the wrong version of the script. I went to the main page https://github.com/DIGITALCRIMINALS/OnlyFans/ and clicked "code" and "download zip", which downloads an old version.

This isn't true. Downloading from code will retrieve the most recent commit that hasn't yet been released as part of releases.

**Comment by jak3-taylor** [comment] 2021-12-09 22:28
Same issue.

**Comment by TheMissingPort** [comment] 2021-12-15 00:56
Same issue

**Comment by stubblesticker** [comment] 2021-12-17 09:35
I'm now having issues again too. Still using v7.6.1, updated cookies and x-bc (nothing changed there), but still cant log in.

**Comment by PsychoSid** [comment] 2021-12-17 10:58
This has returned for me today. Double checked all my values for cookies, x_bc etc all are valid but still being denied.

**Comment by tallglen** [comment] 2021-12-17 19:55
Yup, this was working yesterday and now today something has changed.

**Comment by crazycoug99** [comment] 2021-12-22 05:48
Has there been any update on this? I've been checking some of the other issue posts about this and I'm getting nowhere. All of my values are correct and up to date and yet I'm still getting the BB91C8D6 error.

**Comment by interbiznw** [comment] 2021-12-22 06:11
> Has there been any update on this? I've been checking some of the other issue posts about this and I'm getting nowhere. All of my values are correct and up to date and yet I'm still getting the BB91C8D6 error.

using Docker or from source?

**Comment by crazycoug99** [comment] 2021-12-22 06:41
With my very little coding knowledge I am going to assume source, as I am not using Docker.

**Comment by interbiznw** [comment] 2021-12-22 08:03
> With my very little coding knowledge I am going to assume source, as I am not using Docker.

Oh not sure then, issue I had was a docker issue.

FYI, for future reference Docker is more noob friendly than building from source.. Its basically the 1 click/type to run option

**Comment by TheMissingPort** [comment] 2021-12-23 02:17
> > With my very little coding knowledge I am going to assume source, as I am not using Docker.
> 
> Oh not sure then, issue I had was a docker issue.
> 
> FYI, for future reference Docker is more noob friendly than building from source.. Its basically the 1 click/type to run option

I can't get docker to work for the life of me. It always gives me an error about the dockerfile not being found? And I've tried two different computers

**Closed** 2021-12-27 20:06 UTC
