### ISSUE TITLE
help with this issue

### ISSUE THREAD

**Issue by darkplace77** [DIGITALCRIMINALS/OnlyFans#604] opened 2022-08-25 16:12 UTC
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Stories
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "D:\of\OnlyFans-7.6.1\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\AR15\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\AR15\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\of\OnlyFans-7.6.1\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "D:\of\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "D:\of\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "D:\of\OnlyFans-7.6.1\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "D:\of\OnlyFans-7.6.1\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "D:\of\OnlyFans-7.6.1\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "D:\of\OnlyFans-7.6.1\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "D:\of\OnlyFans-7.6.1\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002740AB5D990>
Traceback (most recent call last):
  File "C:\Users\AR15\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\AR15\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\AR15\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\AR15\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Nick05491** [comment] 2022-08-25 16:16
+1... Just started seeing this error myself as of today.

**Comment by taux1c** [comment] 2022-08-25 16:22
Onlyfans updated the way they determine if there are highlights. It's a simple fix, I've already fixed my repo and came here to fix this one but is so massive I can't seem to chase down where to update it at.

**Comment by Nick05491** [comment] 2022-08-25 16:25
See here: https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518#issuecomment-1192966077

Will try this now...

**Comment by simonchin513** [comment] 2022-08-25 16:27
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518#issuecomment-1227477736
Having the same problem now, sadge

**Comment by Proutbedaine** [comment] 2022-08-25 17:18
yeah same issue here :T
did those fixes a while ago. checked again and they were still fixed as recommended. same issues.

**Comment by tk91787** [comment] 2022-08-25 18:00
Likewise. I made the changes awhile ago, but now I'm getting the same error.

**Comment by MonkeyKingViper** [comment] 2022-08-25 18:03
> https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518#issuecomment-1227477736
Having the same problem now, sadge

EDIT 1: D:\Data\OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
results = [create_highlight(x) for x in results.get("data")]

This fixed this same issue weeks ago.

>TypeError: 'NoneType' object is not iterable

This breaks the script if you add it as you said.

Also, you aren't on the latest commit because "\apis\onlyfans\classes\create_user.py" doesn't exist anymore. It's "apis\onlyfans\classes\user_model.py".

**Comment by eclipseo** [comment] 2022-08-25 18:19
I've sent a quick PR.

Depending on your skill level, grab the patch from the PR and apply it.

Or just replace your file apis/onlyfans/classes/user_model.py with this one https://raw.githubusercontent.com/DIGITALCRIMINALS/OnlyFans/ee736bb44dab23204f9adf3f23cec631c448dd1b/apis/onlyfans/classes/user_model.py

Or wait for the PR to be merged.

**Comment by eclipseo** [comment] 2022-08-25 18:23
To be clear the fix is just modifying apis/onlyfans/classes/user_model.py line 283 and replace `results["data"]]` with `results["list"]]`

**Comment by MonkeyKingViper** [comment] 2022-08-25 19:00
> To be clear the fix is just modifying `apis/onlyfans/classes/user_model.py` line 283 and replace `results["data"]]` with `results["list"]]`

results.get("list")] did work for me, so thank you for the quick work!

**Comment by lordoffools** [comment] 2022-08-25 19:04
The question I have is... what changed? I'm still running the exact same code I was running yesterday.

Did something change on OF's side, or did something change in our dynamically loaded files?

**Comment by eclipseo** [comment] 2022-08-25 19:09
> The question I have is... what changed? I'm still running the exact same code I was running yesterday.
> 
> Did something change on OF's side, or did something change in our dynamically loaded files?

OF changed the way it returns results of its API regarding stories.

**Comment by lordoffools** [comment] 2022-08-25 19:09
> To be clear the fix is just modifying `apis/onlyfans/classes/user_model.py` line 283 and replace `results["data"]]` with `results["list"]]`

What's the change for those running the latest official release (v7.6.1)? Is it still a change in apis/onlyfans/classes/create_user.py as was the case in https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518#issuecomment-1227477736?

**Comment by lordoffools** [comment] 2022-08-25 19:10
> > The question I have is... what changed? I'm still running the exact same code I was running yesterday.
> > Did something change on OF's side, or did something change in our dynamically loaded files?
> 
> OF changed the way it returns results of its API regarding stories.

Got it. Thank you!

**Comment by RB1875** [comment] 2022-08-25 19:47
> > The question I have is... what changed? I'm still running the exact same code I was running yesterday.
> > Did something change on OF's side, or did something change in our dynamically loaded files?
> 
> OF changed the way it returns results of its API regarding stories.

Is there a means by which you can avoid scraping stories? All options will automatically start by scraping stories, resulting in errors.

**Comment by JamiDEV** [comment] 2022-08-25 19:56
it seems like setting the api choice has resolved this and many other issues. 

launch your config file and find these lines under onlyfans supported

"settings": {
        "auto_profile_choice": "1",
        "auto_model_choice": false,
        "auto_media_choice": "2,3,4,5,6,7",
        "auto_api_choice": "2,3,4,5,6,7",
        "browser": {
          "auth": true
        },

you dont have to set auto profile or media choice.

**Comment by mefistos** [comment] 2022-08-25 19:58
> > To be clear the fix is just modifying `apis/onlyfans/classes/user_model.py` line 283 and replace `results["data"]]` with `results["list"]]`
> 
> What's the change for those running the latest official release (v7.6.1)? Is it still a change in apis/onlyfans/classes/create_user.py as was the case in [#518 (comment)](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518#issuecomment-1227477736)?

Same fix but its on line 270 instead :)

**Comment by RB1875** [comment] 2022-08-25 20:04
> it seems like setting the api choice has resolved this and many other issues.
> 
> launch your config file and find these lines under onlyfans supported
> 
> "settings": { "auto_profile_choice": "1", "auto_model_choice": false, "auto_media_choice": "2,3,4,5,6,7", "auto_api_choice": "2,3,4,5,6,7", "browser": { "auth": true },
> 
> you dont have to set auto profile or media choice.

you are an awesome person, thank you

**Comment by left1000** [comment] 2022-08-26 06:00
I am also getting   

File "D:\OnlyFans DataScraper\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results.get("data")]
TypeError: 'NoneType' object is not iterable


not sure what to do. I am running 7.6.1 but with for x in results.get("data") added to the correct file by hand.

because of this I am not sure I want the up to date version https://github.com/DIGITALCRIMINALS/OnlyFans/issues/447

I'm going to try moving all my prior rips, then downloading the current branch of this repo.

**Comment by fightcancer2** [comment] 2022-08-26 06:18
> To be clear the fix is just modifying `apis/onlyfans/classes/user_model.py` line 283 and replace `results["data"]]` with `results["list"]]`

I don't have that file.  Should I be worried?  Here's what I have in ..\classes\

__init__.py            1KB   12/3/2021 9:44 AM   
create_auth.py        18KB   12/3/2021 9:44 AM   
create_highlight.py    1KB   12/3/2021 9:44 AM   
create_message.py      4KB   12/3/2021 9:44 AM   
create_post.py         4KB   12/3/2021 9:44 AM   
create_story.py        2KB   12/3/2021 9:44 AM   
create_user.py        25KB   12/3/2021 9:44 AM   
extras.py              9KB   12/3/2021 9:44 AM

**Comment by fightcancer2** [comment] 2022-08-26 06:53
> 

The file create_user.py on line 270 doesn't have that text. It has:

![image](https://user-images.githubusercontent.com/70211007/186840904-6f092212-4b62-40b2-964f-5096d3cfb618.png)

Can you please confirm?

**Comment by goodboi69691** [comment] 2022-08-26 11:56
> > 
> 
> The file create_user.py on line 270 doesn't have that text. It has:
> 
> ![image](https://user-images.githubusercontent.com/70211007/186840904-6f092212-4b62-40b2-964f-5096d3cfb618.png)
> 
> Can you please confirm?
> 
> EDIT: in version 7.6.1, change line 270 from what it is above to this: results = [create_highlight(x) for x in results.get("list")]

This worked for me.

**Comment by eclipseo** [comment] 2022-09-03 11:04
Bump, I fixed the issue with stories not downloading, same PR #605

Not sure how to deliver changes to people not familiar with Git and Github, you could grab the zip from my branch: https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_api.zip

Or grab the 3 files I have modified (download and copy the raw to the right place)
https://github.com/eclipseo/OnlyFans/blob/44cd15f137c141697b7830057beb83158d3b3660/apis/onlyfans/classes/story_model.py
https://github.com/eclipseo/OnlyFans/blob/44cd15f137c141697b7830057beb83158d3b3660/apis/onlyfans/classes/user_model.py
https://github.com/eclipseo/OnlyFans/blob/44cd15f137c141697b7830057beb83158d3b3660/modules/onlyfans.py

Hope this get merged soon.

**Comment by otisrush** [comment] 2022-09-03 12:30
```
Processing Scraped Messages
  0%|                                                                                          | 0/522 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\XXX\,,,OFN\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\XXX\,,,OFN\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "E:\XXX\,,,OFN\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "E:\XXX\,,,OFN\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "E:\XXX\,,,OFN\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "E:\XXX\,,,OFN\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "E:\XXX\,,,OFN\modules\module_streamliner.py", line 260, in prepare_scraper
    await self.process_scraped_content(master_set, content_type, subscription)
  File "E:\XXX\,,,OFN\modules\module_streamliner.py", line 288, in process_scraped_content
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Python\Python310\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Python\Python310\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Python\Python310\lib\asyncio\tasks.py", line 575, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Python\Python310\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "E:\XXX\,,,OFN\modules\onlyfans.py", line 138, in media_scraper
    preview_link = media["files"]["preview"]["url"]
KeyError: 'url'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027B21CFAB90>
Traceback (most recent call last):
  File "C:\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Getting a similar error but with messages?

**Comment by eclipseo** [comment] 2022-09-03 12:32
how have you iinstalled this "patch"?

**Comment by otisrush** [comment] 2022-09-03 12:33
I swapped all three files, yes

**Comment by eclipseo** [comment] 2022-09-03 12:35
> I swapped all three files, yes

Try with these link instead, I might have pasted the wrong commit. However this is only if you use the latest code, nit the release version.

https://github.com/eclipseo/OnlyFans/blob/master/apis/onlyfans/classes/story_model.py
https://github.com/eclipseo/OnlyFans/blob/master/apis/onlyfans/classes/user_model.py
https://github.com/eclipseo/OnlyFans/blob/master/modules/onlyfans.py

**Comment by otisrush** [comment] 2022-09-03 12:38
As a complete programming noob, which is the "latest version"? I imagine the master is the release.

**Comment by eclipseo** [comment] 2022-09-03 12:48
do you have the

> As a complete programming noob, which is the "latest version"? I imagine the master is the release.

Here you got the released versions: https://github.com/DIGITALCRIMINALS/OnlyFans/releases 
7.6.1 is the latest one.

But there has been changes to the code that has not been in a release yet, this code is located in the "master" branch.
You can get it by clicking the green Code button, then Download ZIP:

![Screenshot_20220903_144327](https://user-images.githubusercontent.com/30413512/188271042-e3b86137-d141-4fd6-aab4-5077c1c53bb8.png)

Another is to download the entire code with fixes I made directly from here https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_api.zip
It contains the master code + the fix already.

**Comment by otisrush** [comment] 2022-09-03 12:51
So again, that's what I've always used. And I applied your fix by swapping the files. Still not working sadly.

**Comment by eclipseo** [comment] 2022-09-03 12:55
Do you have a name of a model it doesn't work with?

**Comment by otisrush** [comment] 2022-09-03 13:10
contesacneajna, baesuicide, ivygehennanoppv, rubyalexia

**Comment by eclipseo** [comment] 2022-09-03 13:23
> ivygehennanoppv

I tried with her and can not repro the issue. 

Could you use this file https://gist.githubusercontent.com/eclipseo/8c499b2a75b0326aadbe4f9d66a1afae/raw/819fb2ea519be7dbd30a6d8418c02cb0fe9b0a7f/onlyfans.py instead and send me the output of the command so I can diagnose it? W/ only one model please.

**Comment by otisrush** [comment] 2022-09-03 13:26
The full output? This is going to be pretty long, should I post it here or is there some other way to do it?

**Comment by Egon099** [comment] 2022-09-03 16:35
> > I swapped all three files, yes
> 
> Try with these link instead, I might have pasted the wrong commit. However this is only if you use the latest code, not the release version.
> 
> https://github.com/eclipseo/OnlyFans/blob/master/apis/onlyfans/classes/story_model.py https://github.com/eclipseo/OnlyFans/blob/master/apis/onlyfans/classes/user_model.py https://github.com/eclipseo/OnlyFans/blob/master/modules/onlyfans.py

isn't user_model.py line 283 still wrong on that link?

**Comment by eclipseo** [comment] 2022-09-03 17:19
It seems so

**Comment by eclipseo** [comment] 2022-09-03 17:20
This is the wrong links, I'm not near a computer right now to fix it, sorry

**Comment by otisrush** [comment] 2022-09-03 17:27
I used the full master + fix zip file, unless that has the wrong files in it as well, it's not an issue. 
The common denominator for all models that are not working for me is that I've sent video files to them via DM. If you have any model you've chatted with and sent her any vids, please try that.

**Comment by eclipseo** [comment] 2022-09-03 17:42
Yeah I don't send vid to people, but if anyone want to get me the output of
the file in the gist I sent before, it will be a big help.

I need to see the output of what it does on media's uploaded by some of
you. Just put it on a Pastebin on I'll dig through it when I get back home.

**Comment by otisrush** [comment] 2022-09-03 17:54
https://pastebin.com/wtAJ53TY

here you go

**Comment by eclipseo** [comment] 2022-09-03 22:23
> https://pastebin.com/wtAJ53TY
> 
> here you go

Could you open this link and tell me if this is a video you uploaded? I'll try not to save your own videos you sent to content creator I think.

https://cdn2.onlyfans.com/files/2/27/276a5fe430925cb2945890008a242f7e/960x540_5b86104f8d0abc3c311d67effb9d6712_frame_378.jpg?Tag=2&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvMlwvMjdcLzI3NmE1ZmU0MzA5MjVjYjI5NDU4OTAwMDhhMjQyZjdlXC85NjB4NTQwXzViODYxMDRmOGQwYWJjM2MzMTFkNjdlZmZiOWQ2NzEyX2ZyYW1lXzM3OC5qcGc~VGFnPTIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NjIzMTM5NjR9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiNDYuMTg2LjI2LjEzM1wvMzIifX19XX0_&Signature=FwHzlelDg-i3nCiG9xd5XJtysZk-rlf1ncZxVtZd-c9X8Ah5Hw8drnGeZjtj~hDB4NXeEsl0D6waUrhO6Xq2yCe7wG2d~sbmXsZfhntBrlqgLi1kkxthAFEjuvwElGLK6TWnWr5rGm7nOW22PPT7pOWs9zY6Q7l8fTAqWGaLTxkcwEREyC0Df5SWfvBgzIy74gH~U44nQeseUEvn-9TTaRJ6sGhwRZLsfaJEgo~kk5EF~tNKv9biuwSXiSvuOUoRPGDySD5Utu-RdNCKEMfIaQ8cP6RGaAD50cekhQAJZaMyO~Fs3TDDTl9lr19b7paq2Zz7S3XrdEf6x6OTCCMKcg__&Key-Pair-Id=APKAJZU4IULC2OKULHGA

**Comment by otisrush** [comment] 2022-09-03 22:44
Yes, it is

**Comment by eclipseo** [comment] 2022-09-03 22:51
Ok,if we skip these files, then 

https://github.com/eclipseo/OnlyFans/blob/80aefb5d3451f68efab2191d723cb9f8202c6230/apis/onlyfans/classes/story_model.py
https://github.com/eclipseo/OnlyFans/blob/80aefb5d3451f68efab2191d723cb9f8202c6230/apis/onlyfans/classes/user_model.py
https://github.com/eclipseo/OnlyFans/blob/80aefb5d3451f68efab2191d723cb9f8202c6230/modules/onlyfans.p

should work, or:

https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_api.zip

should work too/

**Comment by otisrush** [comment] 2022-09-03 22:51
I would prefer it if you removed the previous link btw

**Comment by otisrush** [comment] 2022-09-03 22:59
`Traceback (most recent call last):
  File "E:\XXX\,,,OFN\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "E:\XXX\,,,OFN\helpers\main_helper.py", line 44, in <module>
    from modules.onlyfans import OnlyFansDataScraper
  File "E:\XXX\,,,OFN\modules\onlyfans.py", line 138
    if "preview" in media["files"] and "url" in media["files"]["preview"]
                                                                         ^
SyntaxError: expected ':'`

**Comment by otisrush** [comment] 2022-09-03 22:59
```
Traceback (most recent call last):
  File "E:\XXX\,,,OFN\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "E:\XXX\,,,OFN\helpers\main_helper.py", line 44, in <module>
    from modules.onlyfans import OnlyFansDataScraper
  File "E:\XXX\,,,OFN\modules\onlyfans.py", line 138
    if "preview" in media["files"] and "url" in media["files"]["preview"]
                                                                         ^
SyntaxError: expected ':'
```

**Comment by eclipseo** [comment] 2022-09-03 23:03
> ```
> Traceback (most recent call last):
>   File "E:\XXX\,,,OFN\start_ofd.py", line 9, in <module>
>     from helpers.main_helper import OptionsFormat
>   File "E:\XXX\,,,OFN\helpers\main_helper.py", line 44, in <module>
>     from modules.onlyfans import OnlyFansDataScraper
>   File "E:\XXX\,,,OFN\modules\onlyfans.py", line 138
>     if "preview" in media["files"] and "url" in media["files"]["preview"]
>                                                                          ^
> SyntaxError: expected ':'
> ```



> `Traceback (most recent call last): File "E:\XXX\,,,OFN\start_ofd.py", line 9, in <module> from helpers.main_helper import OptionsFormat File "E:\XXX\,,,OFN\helpers\main_helper.py", line 44, in <module> from modules.onlyfans import OnlyFansDataScraper File "E:\XXX\,,,OFN\modules\onlyfans.py", line 138 if "preview" in media["files"] and "url" in media["files"]["preview"] ^ SyntaxError: expected ':'`

yeah sorry, updated in the meanwhile:


https://raw.githubusercontent.com/eclipseo/OnlyFans/fix_api/apis/onlyfans/classes/story_model.py
https://raw.githubusercontent.com/eclipseo/OnlyFans/fix_api/apis/onlyfans/classes/user_model.py
https://raw.githubusercontent.com/eclipseo/OnlyFans/fix_api//modules/onlyfans.py

or 

https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_api.zip

**Comment by otisrush** [comment] 2022-09-03 23:05
> > https://pastebin.com/wtAJ53TY
> > here you go
> 
> Could you open this link and tell me if this is a video you uploaded? I'll try not to save your own videos you sent to content creator I think.
> 
> https://cdn2.onlyfans.com/files/2/27/276a5fe430925cb2945890008a242f7e/960x540_5b86104f8d0abc3c311d67effb9d6712_frame_378.jpg?Tag=2&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvMlwvMjdcLzI3NmE1ZmU0MzA5MjVjYjI5NDU4OTAwMDhhMjQyZjdlXC85NjB4NTQwXzViODYxMDRmOGQwYWJjM2MzMTFkNjdlZmZiOWQ2NzEyX2ZyYW1lXzM3OC5qcGc~VGFnPTIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NjIzMTM5NjR9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiNDYuMTg2LjI2LjEzM1wvMzIifX19XX0_&Signature=FwHzlelDg-i3nCiG9xd5XJtysZk-rlf1ncZxVtZd-c9X8Ah5Hw8drnGeZjtj~hDB4NXeEsl0D6waUrhO6Xq2yCe7wG2d~sbmXsZfhntBrlqgLi1kkxthAFEjuvwElGLK6TWnWr5rGm7nOW22PPT7pOWs9zY6Q7l8fTAqWGaLTxkcwEREyC0Df5SWfvBgzIy74gH~U44nQeseUEvn-9TTaRJ6sGhwRZLsfaJEgo~kk5EF~tNKv9biuwSXiSvuOUoRPGDySD5Utu-RdNCKEMfIaQ8cP6RGaAD50cekhQAJZaMyO~Fs3TDDTl9lr19b7paq2Zz7S3XrdEf6x6OTCCMKcg__&Key-Pair-Id=APKAJZU4IULC2OKULHGA

could you please remove the link? this whole reply if possible

**Comment by otisrush** [comment] 2022-09-03 23:15
working like a charm now :) thank you for the help!

**Comment by eclipseo** [comment] 2022-09-03 23:15
> > > https://pastebin.com/
> > > here you go
> > 
> > 
> > Could you open this link and tell me if this is a video you uploaded? I'll try not to save your own videos you sent to content creator I think.
> > could you please remove the link? this whole reply if possible

Removed but only you can access it anyway. I can't, that's why I asked it it was one of your upload

**Comment by otisrush** [comment] 2022-09-03 23:15
ah, that's ok. still tho, better safe than sorry

**Comment by alexdevos7** [comment] 2022-09-07 10:45
I downloaded your repo with the fix already applied. I don't get the previous error anymore, but now when I select a model, and choose media type, it creates the folders, downloads nothing and immediately after asks for the media type to download of a different model. and this continues on

**Comment by left1000** [comment] 2022-09-07 12:27
Yeah, so, the master branch, the creating of folders downloading nothing and then moving on to the next model? That's the behavior I saw here https://github.com/DIGITALCRIMINALS/OnlyFans/issues/447

Which is why I'm still using 7.6.1 with as few handmade update/corrections/patches as possible. Something is deeply wrong in between 7.6.1 and the master that renders it not only useless but destructive and harmful :(

**Comment by blairg23** [comment] 2022-09-07 16:52
> 

THIS, this is VERY annoying and needs to be fixed @DIGITALCRIMINALS , pllllleeeease.

**Comment by blairg23** [comment] 2022-09-07 16:52
> Yeah, so, the master branch, the creating of folders downloading nothing and then moving on to the next model? That's the behavior I saw here (where these new folders nuke/delete prior contents) #447
> 
> Which is why I'm still using 7.6.1 with as few handmade update/corrections/patches as possible. Something is deeply wrong in between 7.6.1 and the master that renders it not only useless but destructive and harmful :(

THIS, this is VERY annoying and needs to be fixed @DIGITALCRIMINALS , pllllleeeease.

**Comment by DIGITALCRIMINALS** [comment] 2022-09-07 16:59
I don't know why it's nuking files. 
To even attempt to fix this, I'd need the scraper settings, model database and OnlyFans cookie data to, hopefully recreate the issue.

**Comment by xbbdc** [comment] 2022-09-07 23:57
> I downloaded your repo with the fix already applied. I don't get the previous error anymore, but now when I select a model, and choose media type, it creates the folders, downloads nothing and immediately after asks for the media type to download of a different model. and this continues on

same exact thing is happening to me.

**Comment by eclipseo** [comment] 2022-09-11 15:42
> I downloaded your repo with the fix already applied. I don't get the previous error anymore, but now when I select a model, and choose media type, it creates the folders, downloads nothing and immediately after asks for the media type to download of a different model. and this continues on

That's the behavior I always got. The problem is how the message content is handled I believe. It goes through all messages, even model you haven't selected and then it starts downloading.

**Comment by eclipseo** [comment] 2022-09-13 20:08
> > I downloaded your repo with the fix already applied. I don't get the previous error anymore, but now when I select a model, and choose media type, it creates the folders, downloads nothing and immediately after asks for the media type to download of a different model. and this continues on
> 
> same exact thing is happening to me.



> > Yeah, so, the master branch, the creating of folders downloading nothing and then moving on to the next model? That's the behavior I saw here (where these new folders nuke/delete prior contents) #447
> > Which is why I'm still using 7.6.1 with as few handmade update/corrections/patches as possible. Something is deeply wrong in between 7.6.1 and the master that renders it not only useless but destructive and harmful :(
> 
> THIS, this is VERY annoying and needs to be fixed @DIGITALCRIMINALS , pllllleeeease.



> I downloaded your repo with the fix already applied. I don't get the previous error anymore, but now when I select a model, and choose media type, it creates the folders, downloads nothing and immediately after asks for the media type to download of a different model. and this continues on

Try my PR: https://github.com/DIGITALCRIMINALS/OnlyFans/pull/657
https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_message.zip

**Comment by alexdevos7** [comment] 2022-09-14 14:39
> Try my PR: #657 https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_message.zip

You are a lifesaver! 

It's not working flawlessly. When I select All for the media type, it goes and processes content, lists models again and asks for media type again. After selecting media the second time, it downloads. But that's nothing really, just so glad to have the scraper working and only downloading the selected models haha. Thanks again!!

**Comment by left1000** [comment] 2022-09-14 14:49
Does his PR nuke the folder before downloading into it? (if you repeated your success again would it nuke and redownload?)  Because the "it goes and processes content, lists models again and asks for media type again" step is where the main master branch nukes all your data for that model from prior rips.

**Comment by hydr0homiee** [comment] 2022-09-14 19:32
> hmm I've tried to test it, and it doesn't seem to nuke anything, But I've also run into a few issues now while trying to see if it nukes. I deleted the images folder in Posts -> Free for a model, so that I have stuff to download and check if it nukes previous rips. I choose that model again in the scraper, it created the images folder, but didn't download any of the previously deleted images. Also for 5 or so models it downloaded all the images and video that was shared in messages, but for one model it just downloaded random 2 media files from the conversation (out of like 40+)

The issues you describe with randomly not downloading content have been present in `master` version for a while (#587, #603).

**Comment by left1000** [comment] 2022-09-14 19:50
> > Does his PR nuke the folder before downloading into it? (if you repeated your success again would it nuke and redownload?) Because the "it goes and processes content, lists models again and asks for media type again" step is where the main master branch nukes all your data for that model from prior rips.
> 
> It nukes it without downloading anything. My folders that were nuked only contained the empty folders and occasionally 1-2 random pics/videos. One thing I noticed is the nuked folders seemed to be from models I was no longer subscribed to. This makes me think it's something related to the message scraping as that's the only time the scraper should modify the model's files.
> 
> > hmm I've tried to test it, and it doesn't seem to nuke anything, But I've also run into a few issues now while trying to see if it nukes. I deleted the images folder in Posts -> Free for a model, so that I have stuff to download and check if it nukes previous rips. I choose that model again in the scraper, it created the images folder, but didn't download any of the previously deleted images. Also for 5 or so models it downloaded all the images and video that was shared in messages, but for one model it just downloaded random 2 media files from the conversation (out of like 40+)
> 
> The issues you describe with randomly not downloading content have been present in `master` version for a while (#587, #603).

Yeah, the folders that I had nuked were from models I no longer subscribe to (but I didn't select them, I selected another model I had just subscribed to, but it started going through all models in order, likely looking for messages, deleting entirely any rips I'd previously made of models I had previously subscribed to but no longer did.) Thankfully I had those rips on a backup drive as well.

**Comment by xbbdc** [comment] 2022-09-16 02:11
> > Try my PR: #657 https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_message.zip
> 
> You are a lifesaver!
> 
> It's not working flawlessly. When I select All for the media type, it goes and processes content, lists models again and asks for media type again. After selecting media the second time, it downloads. But that's nothing really, just so glad to have the scraper working and only downloading the selected models haha. Thanks again!!

working the same for me, on the 2nd attempt it does download!

**Comment by Gamma-Velorum** [comment] 2022-09-20 21:27
> "auto_media_choice": "2,3,4,5,6,7",
> you dont have to set auto profile or media choice.

This doesn't seem true for me as It's not downloading any images from posts and messages, only video.

**Comment by burhanilinux** [comment] 2022-09-26 09:03
Nope doesn't work for me

**Closed** 2023-01-31 20:49 UTC
