### ISSUE TITLE
Content Downloaded for Expired Subscription Doesn't Honour `download_directories`

### ISSUE THREAD

**Issue by PsychoSid** [DIGITALCRIMINALS/OnlyFans#748] opened 2023-01-03 07:28 UTC
Hi,

Downloaded the new update (thanks for the continued work BTW). When I run the script models that I am currently subscribed to use the `download_directories` setting in the `config.json` but the ones I have expired and previously bought PPV from just go in the root dir of the script it seems.

Doing some more checks but confident this is the behaviour.

Cheers

**Comment by Kurosaki22** [comment] 2023-01-04 00:26
Yes seeing the same behavior on the latest master

**Comment by DIGITALCRIMINALS** [comment] 2023-02-01 06:15
Does it still put stuff in the root of the directory in the latest commit?
I had similar behaviour and fixed it multiple times.

**Comment by puc9** [comment] 2023-02-02 06:53
> Does it still put stuff in the root of the directory in the latest commit? I had similar behaviour and fixed it multiple times.

I'm not the OP but I've run into the same issue. With the last commit it did not repro.

Thanks a lot for all your work!

**Comment by Kurosaki22** [comment] 2023-02-02 09:25
Yes it seems to be fixed in the latest master.
Cant reproduce it anymore

**Closed** 2023-02-03 00:09 UTC
