### ISSUE TITLE
How to just download one profile?

### ISSUE THREAD

**Issue by wireman21** [DIGITALCRIMINALS/OnlyFans#133] opened 2021-12-03 07:47 UTC
Can someone point me to a link to just set this up to download one profile? I currently have 803 active subscriptions and keep getting this error (thank you in advance):

Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome . | xxxxx
Traceback (most recent call last):
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OnlyFans-7.6\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1845, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\users\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

**Comment by aboredpervert** [comment] 2021-12-03 11:22
Duplicate of #107.

**Closed** 2021-12-03 14:27 UTC
